services:
  trading:
    build: .
    container_name: trading
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./run:/app/run
    environment:
      - TZ=Europe/Rome
    networks:
      - projects

  log-trading:
    image: tsl0922/ttyd
    container_name: log-trading
    restart: unless-stopped
    command: ttyd -p 8080 tail -n 1000 -f /app/logs/trading_bot.log
    volumes:
      - ./logs:/app/logs
    networks:
      - proxy_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_public"
      - "traefik.http.routers.log-trading-router.rule=Host(`trading.local`)"
      - "traefik.http.routers.log-trading-router.entrypoints=web"
      - "traefik.http.services.log-trading-service.loadbalancer.server.port=8080"

networks:
  projects:
    external: true
  proxy_public:
    external: true